#!/bin/sh

IMAGE_PATH=$1
RESIZE=50
RESIZED_PATH=${IMAGE_PATH}_${RESIZE}x${RESIZE}.jpg

export PYTHONPATH=~/caffe/python:${PYTHONPATH}

convert -geometry ${RESIZE}x${RESIZE}! ${IMAGE_PATH} ${RESIZED_PATH}
python classify.py ${RESIZED_PATH}
